src/Entity/Newsletter.php
<?php

namespace App\Entity;

use App\Repository\NewsletterRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewsletterRepository::class)]
class Newsletter
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }
}

templates/render/form_commande.html.twig
{{ form_start(form, {action: path('create_commande', {'id': app.request.attributes.get('id')})}) }}
<div class="col-6 mx-auto mt-3">
	<div class="row">
		<div class="col-6">{{ form_row(form.dateDebut) }}</div>
		<div class="col-6">{{ form_row(form.dateFin) }}</div>
	</div>

	<div class="row">
		<div class="col-6">{{ form_row(form.prenom) }}</div>
		<div class="col-6">{{ form_row(form.nom) }}</div>
	</div>
	<div class="row">
		<div class="col-6">{{ form_row(form.telephone) }}</div>
		<div class="col-6">{{ form_row(form.email) }}</div>
	</div>
	<div class="row mx-auto">
		{{ form_row(form.submit) }}
	</div>
</div>
{{ form_end(form) }}